# Site
repository: sproogen/resume-theme
favicon: images/dev.png

# Content configuration version
version: 2

# Personal info
name: Daniel Cifuentes Cossio
title: Engineering Manager
email: danielcifuentes.54@hotmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  danielcifuentes54
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: danielcifuentes54
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
# - title: itsgoingto.be
  #icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a dedicated DevSecOps professional and Systems Engineer with deep expertise in cloud technologies and microservices architecture. My passion lies in transforming infrastructures and implementing secure, efficient software development life cycles that drive innovation and excellence in software engineering. I specialize in AWS, Terraform, Docker, Kubernetes, Jenkins, and Java, leveraging these tools to create scalable and reliable systems. \n With multiple certifications, including AWS Certified Developer Associate, CKAD, and HashiCorp Vault, I am committed to staying at the forefront of the industry. I excel at optimizing application performance and security, delivering high-quality solutions that solve complex challenges. Fluent in both Spanish and English, I thrive on continuous learning and exploring new technologies to enhance my skills and knowledge. \nThroughout my career, I've been driven by a genuine love for technology and its potential to transform the world. My goal is to bring innovation and excellence to every project I work on, always seeking to solve complex challenges with robust and efficient solutions. I am passionate about advancing the field of DevSecOps, staying updated with the latest industry trends, and contributing to the tech community.

content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: top-middle
  #      title: Super awesome project
  #      link: github.com/sproogen
  #      # link_text: Project Website
  #      additional_links:
  #        - title:  sproogen/modern-resume-theme
  #          icon: fab fa-github
  #          url: github.com/sproogen/modern-resume-theme
  #        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #        #   icon: fab fa-github
  #        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #      quote: >
  #        This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #      description: | # this will include new lines to allow paragraphs
  #        I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Komet Sales
        link: kometsales.com
        link_text: kometsales.com
        sub_title: Engineering Manager
        caption: August 2019 - Present
        quote: >
          Driving innovation through leadership, transforming legacy systems into secure and scalable cloud-native solutions.
        description: | # this will include new lines to allow paragraphs
            Led a global team of DevOps, Cloud, Developers, and Security engineers, transforming infrastructure and managing the full SDLC. Directed the migration from a legacy EC2 monolith to microservices on Kubernetes, ensuring cloud security and compliance. Shaped the company’s DevOps culture and drove adoption of advanced cloud technologies and automation.

      - layout: left
        border: weak
        title: Personalsoft
        link: personalsoft.com
        link_text: personalsoft.com
        sub_title: Senior Software Developer
        caption: May 2019 - August 2019
        quote: >
          Bridging legacy systems with modern solutions to elevate financial services to the next level.
        description: | # this will include new lines to allow paragraphs
            Development of new features for Colombia's largest bank, utilizing Java as the primary programming language. Designed and implemented necessary pipelines for continuous integration and deployment (CI/CD) using Jenkins and Docker. Additionally, improved procedures within the Oracle database for enhanced efficiency.

      - layout: left
        border: weak
        title: Process On Line
        link: https://www.linkedin.com/company/processonlinebpms/?originalSubdomain=co
        link_text: pol.com
        sub_title: Senior Software Developer
        caption: July 2018 - May 2019
        quote: >
          Harnessing innovative technologies to create cutting-edge solutions in the healthcare domain.
        description: | # this will include new lines to allow paragraphs
            Senior Java Developer leading the development of a new product for a health company. Leveraging technologies such as Java, Spring Boot, Docker, Docker Compose, RabbitMQ, React, and Bitbucket to build innovative solutions.

      - layout: left
        border: weak
        title: Su Red
        link: https://www.sured.com.co/
        link_text: sured.com.co
        sub_title: Junior Software Developer
        caption: April 2016 - July 2018
        quote: >
          Delivering seamless user experiences by optimizing betting services with precision and innovation.
        description: | # this will include new lines to allow paragraphs
            Java Developer responsible for designing and implementing new features for the company’s betting services, focusing on optimizing and advancing functionality in the gambling sector.

      - layout: left
        border: weak
        title: Gana
        link: https://www.gana.com.co/
        link_text: gana.com.co
        sub_title: Technical Support Agent
        caption: November 2013 - April 2016
        quote: >
          Ensuring operational excellence by resolving challenges with technical expertise and dedication.
        description: | # this will include new lines to allow paragraphs
            Technical Support Assistant responsible for resolving issues with Linux operating systems and Java applications used in betting services.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Systems Egineering - Bachelor Degree 
        caption: 2014 - 2019
        sub_title: ITM (Instituto Tecnológico Metropolitano)

      - layout: top-middle
        title: Security Information - Associate
        caption: 2019 - 2019
        sub_title: ITM (Instituto Tecnológico Metropolitano)
      
      - layout: top-middle
        title: Systems Information - Associate
        caption: 2014 - 2017
        sub_title: ITM (Instituto Tecnológico Metropolitano)

      - layout: top-middle
        title: Networking and Computers Administration - Associate
        caption: 2012 - 2013
        sub_title: SENA (Servicio Nacional de Aprendizaje)

  - title: International Certifications
    layout: text
    content: | # this will include new lines to allow paragraphs Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - [HashiCorp Certified: Vault Associate (002)](https://www.credly.com/badges/f3183976-bdf3-4221-a190-7319dfa16c30/linked_in_profile)
      - [GitOps Certified](https://drive.google.com/file/d/1KNYK_RJvLYfAy5bNNYL7qGB7285Dd0B2/view)
      - [DevOps Essentials Professional Certificate - DEPC](https://www.credly.com/badges/56a92340-e9d8-4f41-8b47-9e7065d3d276/linked_in_profile)
      - [AWS Certified Developer – Associate](https://www.credly.com/badges/f4789717-7d85-49a8-8046-8109a4eaccad/linked_in_profile)
      - [CKAD: Certified Kubernetes Application Developer](https://www.credly.com/badges/db617e80-da7a-4e6c-878d-c7097d6687b3/linked_in_profile)
      - [Fundamentals for Istio by Solo.io](https://www.credly.com/badges/2e0ee711-1cd8-4fef-94e3-3d10155b4820/linked_in_profile)
      - [HashiCorp Certified: Terraform Associate (002)](https://www.credly.com/badges/92a93b84-c616-41a8-adf5-50013c2a80eb/linked_in_profile)
      - [Software Architect (Microservices)](https://www.edureka.co/my-certificate/25ae25a77f15cd622cd638021ccb3102)
      - [API Security Architect](https://drive.google.com/file/d/1c-p63WeHZMaKk7B9vROz4S3wZ9W0eNgr/view)
      - [API Designer](https://drive.google.com/file/d/11ZVdJH6UV1nqakQIo782vRo5ZsmYhTy9/view)
      - [AWS Certified Cloud Practitioner](https://www.credly.com/badges/26d88a63-b8e9-4d20-b412-13779dc3dda9/linked_in_profile)
      - [Completion Award for Oracle MOOC: PL/SQL Fundamentals (2018)](https://www.credly.com/badges/42fb4def-d095-4556-98cb-c73dc881d91e/linked_in_profile)
      - [Completion Award for Oracle MOOC: Introduction to PL/SQL Program Units](https://www.credly.com/badges/6e2ccd16-7e6f-4b11-a572-c93563618294/linked_in_profile)
      - [Completion Award for Oracle MOOC: SQL Fundamentals (2018)](https://www.credly.com/badges/e036e48e-05a4-452a-becd-780df1084023/linked_in_profile)
      - [Scrum Master](https://www.scrum-institute.org/badges/73914934702217)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
